autoscaling:
  enabled: true
  minReplicas: 10
  maxReplicas: 10
  targetCPUUtilizationPercentage: "75"
  targetMemoryUtilizationPercentage: "75"

image:
  registry: docker.io
  repository: mosipid/websub-service
  tag: 1.2.0.1
  pullPolicy: IfNotPresent
  pullSecrets:
    - dockerhub

nodeSelector:
  vlan: "200"

additionalResources:
  javaOpts: "-Xms3000M -Xmx3000M"

resources:
  requests:
    cpu: 2
    memory: 7Gi
  limits:
    cpu: 2
    memory: 7Gi

extraEnvVarsCM:
  - global
  - config-server-share
  - artifactory-share
