autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: "75"
  targetMemoryUtilizationPercentage: "75"

image:
  registry: docker.io
  repository: niradocker/registration-processor-reprocessor-new
  tag: prod_22112025
  pullPolicy: IfNotPresent
  pullSecrets:
    - dockerhub

nodeSelector:
  vlan: "200"

additionalResources:
  javaOpts: "-Xms1250M -Xmx1250M"

resources:
  limits:
    cpu: 500m
    memory: "2560Mi"
  requests:
    cpu: 500m
    memory: "2560Mi"

extraEnvVarsCM:
  - global
  - config-server-share
  - artifactory-share
