istio:
  enabled: true
  hosts:
    - activemq.xyz.abc.net
  ingressController:
    name: ingressgateway-internal
  prefix: /

nodeSelector:
  vlan: "200"

replicaCount: 15

resources:
  limits:
    cpu: "1"
    memory: "3Gi"
  requests:
    cpu: "1"
    memory: "3Gi"

hpa:
  enabled: false
  maxReplicas: 19
  # average total CPU usage per pod (1-100)
  cpu: 75
  # average memory usage per pod (100Mi-1Gi)
  memory: 75
  # requests: "500m"