autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 8
  targetCPUUtilizationPercentage: "75"
  targetMemoryUtilizationPercentage: "75"

image:
  registry: docker.io
  repository: mosipid/policy-management-service
  tag: "1.2.0.1"
  pullPolicy: IfNotPresent
  pullSecrets:
    - dockerhub

nodeSelector:
  vlan: "200"

additionalResources:
  javaOpts: "-Xms2250M -Xmx2250M"

resources:
  limits:
    cpu: "500m"
    memory: "3000Mi"
  requests:
    cpu: "400m"
    memory: "2Gi"

extraEnvVarsCM:
  - global
  - config-server-share
  - artifactory-share
