autoscaling:
  enabled: true
  minReplicas: 20
  maxReplicas: 20
  targetCPUUtilizationPercentage: "75"
  targetMemoryUtilizationPercentage: "75"

image:
  registry: docker.io
  repository: niradocker/id-repository-identity-service
  tag: prod_14102025
  pullPolicy: IfNotPresent
  pullSecrets:
  - dockerhub

nodeSelector:
  vlan: "200"

additionalResources:
  ## Specify any JAVA_OPTS string here. These typically will be specified in conjunction with above resources
  ## Example: java_opts: "-Xms500M -Xmx500M"
  javaOpts: "-Xms4500M -Xmx4500M"

resources:
  limits:
    cpu: "2"
    memory: "6Gi"
  requests:
    cpu: "2"
    memory: "6Gi"

extraEnvVarsCM:
  - global
  - config-server-share
  - artifactory-share
