autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: "75"
  targetMemoryUtilizationPercentage: "75"

image:
  registry: docker.io
  repository: niradocker/credential-service
  tag: prod-05082025
  pullPolicy: IfNotPresent
  pullSecrets:
  - dockerhub

nodeSelector:
  vlan: "200"

additionalResources:
  ## Specify any JAVA_OPTS string here. These typically will be specified in conjunction with above resources
  ## Example: java_opts: "-Xms500M -Xmx500M"
  javaOpts: "-Xms2000M -Xmx2000M -XX:MaxDirectMemorySize=4000M -XX:MaxMetaspaceSize=256M"

resources:
  limits:
    cpu: "1"
    memory: "8Gi"
  requests:
    cpu: "1"
    memory: "8Gi"

extraEnvVarsCM:
  - global
  - config-server-share
  - artifactory-share
