clusterDomain: cluster.local
logRetentionBytes: _1073741824
defaultReplicationFactor: 3
offsetsTopicReplicationFactor: 3
transactionStateLogReplicationFactor: 3
numPartitions: 20
replicaCount: 5
sidecars: {}
autoCreateTopicsEnable: true
# CAUTION: Option to delete topics should be disabled in production.
# Env vars: KAFKA_CFG_DELETE_TOPIC_ENABLE=false
deleteTopicEnable: false
nodeSelector:
  vlan: "202"
image:
  pullPolicy: IfNotPresent
  repository: "niradocker/kafka"
  tag: "prod-26092025"
  pullSecrets:
  - dockerhub

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 8Gi

zookeeper:
  replicaCount: 5
  nodeSelector:
    vlan: "202"
  image:
    pullPolicy: IfNotPresent
    repository: "niradocker/kafka"
    tag: "prod-26092025"
    pullSecrets:
    - dockerhub
  resources:
    limits:
      memory: 2000Mi
      cpu: 350m
    requests:
      memory: 2000Mi
      cpu: 350m
  persistence:
    enabled: true
    size: 2Gi

resources:
  limits:
    cpu: "2"
    memory: 6Gi
  requests: 
    cpu: "2"
    memory: 6Gi

startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 30
  successThreshold: 1


rbac:
  create: true
