autoscaling:
  enabled: true
  minReplicas: 8
  maxReplicas: 20
  targetCPUUtilizationPercentage: "90"
  targetMemoryUtilizationPercentage: "75"

image:
  registry: docker.io
  repository: mosipid/kernel-auditmanager-service
  tag: "1.2.0.1"
  pullPolicy: IfNotPresent
  pullSecrets:
    - dockerhub

nodeSelector:
  vlan: "200"

additionalResources:
  javaOpts: "-Xms2000M -Xmx2000M"

resources:
  limits:
    cpu: "1"
    memory: "3000Mi"
  requests:
    cpu: "1"
    memory: "3000Mi"

extraEnvVarsCM:
  - global
  - config-server-share
  - artifactory-share
